// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/search/search.proto

package search

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Video struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Thumbnail            string   `protobuf:"bytes,4,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}
func (*Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_939d9f54669eb8a6, []int{0}
}

func (m *Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Video.Unmarshal(m, b)
}
func (m *Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Video.Marshal(b, m, deterministic)
}
func (m *Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Video.Merge(m, src)
}
func (m *Video) XXX_Size() int {
	return xxx_messageInfo_Video.Size(m)
}
func (m *Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Video proto.InternalMessageInfo

func (m *Video) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Video) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Video) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Video) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

type SearchRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_939d9f54669eb8a6, []int{1}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SearchResponse struct {
	Video                *Video   `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_939d9f54669eb8a6, []int{2}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

func init() {
	proto.RegisterType((*Video)(nil), "Video")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

func init() { proto.RegisterFile("proto/search/search.proto", fileDescriptor_939d9f54669eb8a6) }

var fileDescriptor_939d9f54669eb8a6 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xcf, 0x4b, 0x87, 0x40,
	0x10, 0xc5, 0xf3, 0x27, 0x38, 0x91, 0xc5, 0x9c, 0xb6, 0xf0, 0x10, 0xdb, 0x25, 0x3a, 0x6c, 0x60,
	0xc7, 0xfe, 0x0b, 0x85, 0x2e, 0x9d, 0x56, 0x1d, 0x70, 0x41, 0x5d, 0xdb, 0x55, 0xff, 0xfe, 0x70,
	0x4a, 0xbe, 0x08, 0xdf, 0xd3, 0x3c, 0x3e, 0x3c, 0xde, 0x7b, 0x03, 0x8f, 0xb3, 0xb3, 0x8b, 0x7d,
	0xf7, 0xa4, 0x5d, 0xdb, 0xff, 0x1f, 0xc5, 0x4c, 0x7e, 0x43, 0xf2, 0x65, 0x3a, 0xb2, 0x88, 0x10,
	0x4f, 0x7a, 0x24, 0x11, 0x3c, 0x07, 0xaf, 0x59, 0xc5, 0x1a, 0x1f, 0x20, 0x5a, 0xdd, 0x20, 0x42,
	0x46, 0xbb, 0xc4, 0x1c, 0x42, 0xd3, 0x89, 0x88, 0x41, 0x68, 0x3a, 0x2c, 0x20, 0x5b, 0xfa, 0x75,
	0x6c, 0x26, 0x6d, 0x06, 0x11, 0x33, 0xbe, 0x00, 0xf9, 0x02, 0x77, 0x35, 0x97, 0x55, 0xf4, 0xb3,
	0x92, 0x5f, 0xae, 0x95, 0x48, 0x05, 0xf9, 0x61, 0xf2, 0xb3, 0x9d, 0x3c, 0x61, 0x01, 0xc9, 0xb6,
	0x6f, 0x62, 0xdb, 0x6d, 0x99, 0x2a, 0x5e, 0x58, 0xfd, 0xc1, 0xf2, 0xf3, 0x08, 0xad, 0xc9, 0x6d,
	0xa6, 0x25, 0x7c, 0x83, 0xa4, 0x26, 0xdd, 0xf6, 0x98, 0xab, 0x53, 0xdb, 0xd3, 0xbd, 0x3a, 0x07,
	0xcb, 0x9b, 0x26, 0xe5, 0xaf, 0x3f, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x78, 0x25, 0xc3, 0x6e,
	0x12, 0x01, 0x00, 0x00,
}
