// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/search/search.proto

package search

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error_Type int32

const (
	Error_NIL Error_Type = 0
)

var Error_Type_name = map[int32]string{
	0: "NIL",
}

var Error_Type_value = map[string]int32{
	"NIL": 0,
}

func (x Error_Type) String() string {
	return proto.EnumName(Error_Type_name, int32(x))
}

func (Error_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_939d9f54669eb8a6, []int{0, 0}
}

type Error struct {
	Type                 Error_Type `protobuf:"varint,1,opt,name=type,proto3,enum=Error_Type" json:"type,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Cause                *Error     `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_939d9f54669eb8a6, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetType() Error_Type {
	if m != nil {
		return m.Type
	}
	return Error_NIL
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetCause() *Error {
	if m != nil {
		return m.Cause
	}
	return nil
}

type Video struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Thumbnail            string   `protobuf:"bytes,4,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}
func (*Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_939d9f54669eb8a6, []int{1}
}

func (m *Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Video.Unmarshal(m, b)
}
func (m *Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Video.Marshal(b, m, deterministic)
}
func (m *Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Video.Merge(m, src)
}
func (m *Video) XXX_Size() int {
	return xxx_messageInfo_Video.Size(m)
}
func (m *Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Video proto.InternalMessageInfo

func (m *Video) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Video) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Video) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Video) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

type SearchRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_939d9f54669eb8a6, []int{2}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SearchResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Video                *Video   `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_939d9f54669eb8a6, []int{3}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *SearchResponse) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

func init() {
	proto.RegisterEnum("Error_Type", Error_Type_name, Error_Type_value)
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*Video)(nil), "Video")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

func init() { proto.RegisterFile("proto/search/search.proto", fileDescriptor_939d9f54669eb8a6) }

var fileDescriptor_939d9f54669eb8a6 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x9b, 0xcf, 0x92, 0x29, 0x6f, 0x5a, 0xe6, 0x94, 0x57, 0x0a, 0x86, 0xf5, 0x12, 0x10,
	0x22, 0xc4, 0xab, 0x57, 0x0f, 0x42, 0xf1, 0xb0, 0x15, 0x2f, 0x9e, 0xd2, 0x64, 0xb0, 0x81, 0xe6,
	0xa3, 0xbb, 0x49, 0xa1, 0xff, 0xbd, 0x64, 0xb6, 0x51, 0x0b, 0x9e, 0x76, 0xf6, 0x37, 0xb3, 0xf3,
	0x3c, 0x0f, 0x0b, 0xff, 0x3b, 0xd5, 0xf6, 0xed, 0x83, 0xa6, 0x5c, 0x15, 0xfb, 0xcb, 0x91, 0x32,
	0x13, 0x47, 0xf0, 0x9e, 0x95, 0x6a, 0x15, 0xde, 0x82, 0xdb, 0x9f, 0x3b, 0x8a, 0xac, 0xd8, 0x4a,
	0xc2, 0x6c, 0x91, 0x32, 0x4d, 0xdf, 0xce, 0x1d, 0x49, 0x6e, 0x60, 0x04, 0xf3, 0x9a, 0xb4, 0xce,
	0x3f, 0x29, 0xb2, 0x63, 0x2b, 0x09, 0xe4, 0x74, 0xc5, 0x35, 0x78, 0x45, 0x3e, 0x68, 0x8a, 0x9c,
	0xd8, 0x4a, 0x16, 0x99, 0x6f, 0xde, 0x4a, 0x03, 0xc5, 0x12, 0xdc, 0x71, 0x0b, 0xce, 0xc1, 0x79,
	0x7d, 0xd9, 0xac, 0x66, 0xe2, 0x03, 0xbc, 0xf7, 0xaa, 0xa4, 0x16, 0x11, 0xdc, 0x26, 0xaf, 0x8d,
	0x64, 0x20, 0xb9, 0xc6, 0x15, 0x38, 0x83, 0x3a, 0x5c, 0x14, 0xc6, 0x12, 0x43, 0xb0, 0xab, 0x92,
	0x57, 0x07, 0xd2, 0xae, 0x4a, 0x5c, 0x43, 0xd0, 0xef, 0x87, 0x7a, 0xd7, 0xe4, 0xd5, 0x21, 0x72,
	0x19, 0xff, 0x00, 0x71, 0x07, 0xff, 0xb6, 0x9c, 0x4f, 0xd2, 0x71, 0x20, 0xdd, 0xff, 0x25, 0x22,
	0x36, 0x10, 0x4e, 0x43, 0xba, 0x6b, 0x1b, 0xcd, 0x11, 0x68, 0x34, 0xcd, 0x63, 0xbf, 0x22, 0x30,
	0x1c, 0xbb, 0xa7, 0xd1, 0xf1, 0x77, 0x40, 0xf6, 0x2f, 0x0d, 0xcc, 0x9e, 0x26, 0xc9, 0x2d, 0xa9,
	0x53, 0x55, 0x10, 0xde, 0x83, 0x6f, 0x00, 0x86, 0xe9, 0x95, 0x99, 0x9b, 0x65, 0x7a, 0xad, 0x2b,
	0x66, 0x3b, 0x9f, 0xff, 0xe1, 0xf1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x20, 0x0a, 0x65, 0x65, 0xa4,
	0x01, 0x00, 0x00,
}
