// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/encode/encode.proto

package encode

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EncodeRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncodeRequest) Reset()         { *m = EncodeRequest{} }
func (m *EncodeRequest) String() string { return proto.CompactTextString(m) }
func (*EncodeRequest) ProtoMessage()    {}
func (*EncodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc5415be466f50e3, []int{0}
}

func (m *EncodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncodeRequest.Unmarshal(m, b)
}
func (m *EncodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncodeRequest.Marshal(b, m, deterministic)
}
func (m *EncodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodeRequest.Merge(m, src)
}
func (m *EncodeRequest) XXX_Size() int {
	return xxx_messageInfo_EncodeRequest.Size(m)
}
func (m *EncodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EncodeRequest proto.InternalMessageInfo

func (m *EncodeRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type EncodeResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Opus                 []byte   `protobuf:"bytes,2,opt,name=opus,proto3" json:"opus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncodeResponse) Reset()         { *m = EncodeResponse{} }
func (m *EncodeResponse) String() string { return proto.CompactTextString(m) }
func (*EncodeResponse) ProtoMessage()    {}
func (*EncodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc5415be466f50e3, []int{1}
}

func (m *EncodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncodeResponse.Unmarshal(m, b)
}
func (m *EncodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncodeResponse.Marshal(b, m, deterministic)
}
func (m *EncodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodeResponse.Merge(m, src)
}
func (m *EncodeResponse) XXX_Size() int {
	return xxx_messageInfo_EncodeResponse.Size(m)
}
func (m *EncodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EncodeResponse proto.InternalMessageInfo

func (m *EncodeResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EncodeResponse) GetOpus() []byte {
	if m != nil {
		return m.Opus
	}
	return nil
}

func init() {
	proto.RegisterType((*EncodeRequest)(nil), "EncodeRequest")
	proto.RegisterType((*EncodeResponse)(nil), "EncodeResponse")
}

func init() { proto.RegisterFile("proto/encode/encode.proto", fileDescriptor_cc5415be466f50e3) }

var fileDescriptor_cc5415be466f50e3 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcd, 0x4b, 0xce, 0x4f, 0x49, 0x85, 0x52, 0x7a, 0x60, 0x31, 0x25, 0x45, 0x2e,
	0x5e, 0x57, 0x30, 0x3f, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x80, 0x8b, 0xb9, 0xb4,
	0x28, 0x47, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x54, 0x32, 0xe3, 0xe2, 0x83, 0x29,
	0x29, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xc5, 0x54, 0x23, 0x24, 0xc4, 0xc5, 0x92, 0x5f, 0x50, 0x5a,
	0x2c, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x1b, 0xd9, 0xc1, 0x8c, 0x0e, 0x4e, 0x2d,
	0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xd2, 0xe5, 0x62, 0x83, 0x08, 0x08, 0xf1, 0xe9, 0xa1, 0x58, 0x2a,
	0xc5, 0xaf, 0x87, 0x6a, 0x83, 0x12, 0x83, 0x01, 0x63, 0x12, 0x1b, 0xd8, 0x85, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc7, 0x96, 0x22, 0x15, 0xbe, 0x00, 0x00, 0x00,
}
